### ISSUE TITLE
Non-ascii names result in error while creating slug

### ISSUE THREAD

**Issue by pors** [roygreenfeld/django-crash-course#126]
## Location within the Book

* Chapter: 45.7 Resubmit the Form

## Description 

When adding the very tasty Greek cheese "Κεφαλοτύρι" the error `django slug is defined before trying to ensure uniqueness` is returned.

This can be solved by installing this library: [Unidecode](https://pypi.org/project/Unidecode/), which is used by django-autoslug when needed.

**Comment by pydanny** [comment]
Oh goodness, `Κεφαλοτύρι` (https://en.wikipedia.org/wiki/Kefalotyri) looks delicious. We never knew we were eating Spanakopita with the wrong cheese, which is why that dish always disappointed. We're going to start checking cheese mongers in Southern California for Κεφαλοτύρι. We know this will really help with the quality of our life, not to mention the book.

Speaking of the book, this is an excellent point. We need to add Κεφαλοτύρι to the book. We must do this ASAP!!! 🇬🇷🧀 

Oh yeah, I guess we'll also mention `unidecode` as well. Not quite as important or urgent as adding Κεφαλοτύρι, but we'll get around to it. 😉

**Comment by pydanny** [comment]
🚢 🧀

**Comment by pors** [comment]
Haha, you're welcome. I love the book! And Κεφαλοτύρι!
