### ISSUE TITLE
Section 15.5.1 rendering issue

### ISSUE THREAD

**Issue by omaciel** [roygreenfeld/django-crash-course#49]
## Location within the Book

* Chapter or Appendix: 15
* Section: 5
* Subsection: 1

## Description 

The following section shows rendering issues (not wrapping around the right margin) on Mac OS Preview Version 11.0 (999.4) when viewing the PDF version of the book, as shown by the screenshot included here.

```
You've cloned /Users/audreyr/[.......]
```

I wonder if you need to escape the apostrophe after the word **You**?

<img width="1059" alt="Screen Shot 2020-02-12 at 6 00 46 PM" src="https://user-images.githubusercontent.com/53362/74385724-37992900-4dc2-11ea-85a5-0f9b75f99e2c.png">

**Comment by audreyr** [comment]
Thanks for the awesomely clear bug report, plus the detective work about escaping the apostrophe @omaciel!

I've fixed this for the next release:
* I ended up changing the fenced code block in our RMarkdown book chapter file from `bash` to `plaintext`
* I manually wrapped the lines since RMarkdown fenced code blocks display as-is
* Updated changelog and double-checked attribution

🚢 🧀

**Comment by omaciel** [comment]
Thanks for the kind words, @audreyr I guess writing bug reports comes naturally after years working as a quality engineer :) I'll finish reading the book this next week and will send more reports as I come across anything worth reporting.

Have a great weekend!
