### ISSUE TITLE
cheese.get_firmness_display causes the template to fail

### ISSUE THREAD

**Issue by AhnafCodes** [roygreenfeld/django-crash-course#53]
## Location within the Book

* Chapter or Appendix: 37 The Cheese Detail Template
* Section: 37.1
* Subsection:  cheese_detail.html Code section

## Description 

```
{% if cheese.firmness %}
<p>Firmness: {{ cheese.get_firmness_display }}</p>
``` 
cheese.get_firmness_display  cause the template to fail, Error

I know don't if this would work if the "Firmness" is a class in  model.py as in your repo i.e. https://gitlab.com/pydanny/everycheese/-/blob/master/everycheese/cheeses/models.py. This is different from the model in the book  in section 26.6.4  its a tuple as below
```
FIRMNESS_CHOICES = (
(FIRMNESS_UNSPECIFIED, "Unspecified"),
(FIRMNESS_SOFT, "Soft"),
(FIRMNESS_SEMI_SOFT, "Semi-Soft"),
(FIRMNESS_SEMI_HARD, "Semi-Hard"),
(FIRMNESS_HARD, "Hard"),
)
# Other Fields Here...
firmness = models.CharField("Firmness", max_length=20,
choices=FIRMNESS_CHOICES, default=FIRMNESS_UNSPECIFIED)
```

**Comment by pydanny** [comment]
Hey @AhnafCodes, I'll look into that ASAP. Thanks forth catch!

**Comment by pydanny** [comment]
@AhnafCodes Can you paste in the details of the error message? Either a screen shot or code paste would be great. Otherwise I can't diagnose your problem.

Also, the everycheese repo on gitlab is where we test code changes in the book. We don't advertise it because it's not stable.

That said, we are switching our choices controls to Django 3-style enums in the update coming later today. 😄

**Comment by pydanny** [comment]
@AhnafCodes, I'm going to close this issue. If it should remain open, go ahead and reopen it or comment that it should be reopened.
